/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function ping(): string
export declare function compress(text: string, level: string): string
export interface CompressionInfo {
  compressed: string
  originalLen: number
  compressedLen: number
  ratio: number
}
export declare function compressDetailed(text: string, level: string): CompressionInfo
export interface RoutingResult {
  model: string
  tier: string
  confidence: number
  reasoning: string
}
export declare function route(prompt: string, profile: string): RoutingResult
export declare function createSession(userId?: string | undefined | null): string
export interface VectorSearchResult {
  id: string
  score: number
}
export declare function vectorSearch(query: Array<number>, vectorsJson: string, topK?: number | undefined | null): Array<VectorSearchResult>
export declare function searchContext(query: string, topK?: number | undefined | null): Array<VectorSearchResult>
