/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function ping(): string
export interface MemoryEntry {
  id: string
  sessionId: string
  userId: string
  category: string
  content: string
  overview: string
  language: string
  createdAt: string
}
export interface AddMemoryResult {
  id: string
  category: string
  stored: boolean
}
/** Add a memory entry. Extracts category heuristically if not provided. */
export declare function addMemory(content: string, userId: string, sessionId?: string | undefined | null, category?: string | undefined | null): AddMemoryResult
/** Search memories by query string (simple text matching). */
export declare function searchMemory(query: string, userId?: string | undefined | null, category?: string | undefined | null, limit?: number | undefined | null): Array<MemoryEntry>
export interface SessionInfo {
  id: string
  userId: string
  state: string
  messageCount: number
  totalTurns: number
  createdAt: string
  updatedAt: string
}
export declare function createSession(userId?: string | undefined | null): SessionInfo
export declare function getSession(sessionId: string): SessionInfo
export declare function listSessions(userId?: string | undefined | null): Array<SessionInfo>
/** Add a message to a session. */
export declare function addSessionMessage(sessionId: string, role: string, content: string): boolean
/** Close a session. */
export declare function closeSession(sessionId: string): boolean
export declare function compress(text: string, level: string): string
export interface CompressionInfo {
  compressed: string
  originalLen: number
  compressedLen: number
  ratio: number
}
export declare function compressDetailed(text: string, level: string): CompressionInfo
export interface RoutingResult {
  model: string
  tier: string
  confidence: number
  reasoning: string
}
export declare function route(prompt: string, profile: string): RoutingResult
export interface VectorSearchResult {
  id: string
  score: number
}
export declare function vectorSearch(query: Array<number>, vectorsJson: string, topK?: number | undefined | null): Array<VectorSearchResult>
export interface ExtractedMemory {
  category: string
  content: string
  overview: string
  language: string
}
/** Extract memory candidates from session messages. */
export declare function extractMemories(sessionId: string): Array<ExtractedMemory>
